language: android
android:
  components:
  - tools
  - tools
  - platform-tools
  - build-tools-24.0.2
  - android-24
  - extra-android-m2repository
jdk:
- oraclejdk8
before_script:
- rm -rf ~/.gradle/caches/
script:
- ./gradlew ":noadapter:build"
after_success:
- ".buildscript/deploy_snapshot.sh"
env:
  global:
  - secure: f3qS4/MfTmcBWmxRJNuhTfeifaZXM2nmwKzNHCYha8lZ/+hFQcUbE1hJATOoRjdaRzIPgtouHSf7HgwKBfVPCNj35zee9cVO1TCfRPfr5rqLgvcmgiYnaeyVX0JVveH4AjwOjGJLXqVyMlDy/Y9ol7fW7OQDkz403As+oYxUvzi3MaRQAby56YWIDkHLEgcK5C20dvxS+e6/2wxVXG2D6woyG8D0xE0H7/n8pWwiF5Spby+9UcjwJ26lD8/XTIvtIcLgFVIYfW79ANLKhm8+i7t5BQ45CeRARCPVoQ1XkJiCST/P9V5OY1Gz+VFFHWKW85QPB9SXbcilSbxLmDRQA7snA5GUbR+E1aGdKEjfYVecz/TJioBlwOVjDLUPLoaT0Mi3RY1K+Yu8RIPl64fxQ2Ik2uQhGY0freCeaO/2v7zs0p2e/IfxpwNb8yWeywhSGcoqY6tBSPTH0LPRmb9ux6p+9xwxGctr9MtK+Z0AXKgLvAts9tzTAsQWlI6hvlhUjES63PjGwbZWAuBjF0pFeDrlYN94l3dCDDp8oK3oIbbEGD+tFyiBNQ96ArlJU56AeyHnZN9PVx9ckmsD1tHfKUFG6UmzWAc+jTx97WI44i8vKhWq3dG1ywNHY2gXxVopO36av3KTupoC9xB5Mm3qk3HVIXETbzLCRNvf+0iPQFE=
  - secure: t4pz7/srM3VIg5PveUR64HDWe36CNS1paUs9mGXPrcP6Ug5oyUbGjPzTnffuaT/tIPaRMF01t/swKjDIadfBBgM+1JMy3eMrK2W+EnxzZRNSJ5GyvA7CHMuEIzp9RGj3yrMDxUS2h2dT9IMYQ1FHMdnpgtS2Vzl9d/1Z1gaxsY7ll4jr66Ri9gvo+MAwZsXtkoH0MrpCmaBpnnfED4JOnGKzFQds2DR9eIJ1LkJ5tgLMpEeJiEEhua/Krs/TIzXgdW8f6q5ke2h8Xn0tGBt6pvKNXGa4eioqxqmcJbSbfbqCweDwxNQGzaVWMAl9hEe6UxnXZTjUSmJJizItVpRN5DuKOzI5KnFnFd2C2NKDOcXJwnmP4VOtsc+OGMtxkkLuUi6D7wsgDagNAKJ2PgNxZAfyRDOC/RsdrXyLYZv9T/Y1UqIvxyk7I9OOkIgmRn2wla9qrcwCm/UoebbLaPYrcIC0y8NCh3OzQKzraDVuwkhtbIqx/lN8bMCJbhfu7VCyZn3tNWJVX5eFTDtVa9XlQyTdGF3cnpoZxSxSg0Ex9prJ14jol+Jhmr4xzmH9rU2elt7hsixypVU5UPwpsahKr9+EBx8e9t3x80mlbcDFLZ1hZpakBOvZMTNIcZw+Cr2lnIRtNW8HFzc18TLJGIcOjNcnci0QmW3v9EvVN/RxWXw=
  - secure: iWGmrogZ9as+TguVSQDMeRexSlprRvMRSZoDsV/DYQ366fdDXZVPAItI4fEZcYaly9WOPGHIIa0O7qJ1xbcHtEWvBigHnfiogO4PXXsF8FAX50AFcdJAFv5eL+RlM9Sck2mkSrsqHxEWG2/n6DDrjheqOeFZk1v4MIUtZYlgezgarJlPG6zDoW6XBeWWS2wFblyTskN30RagC8hjScrs1uNgpwWf7VvhlUzKun4Y47ntzBIadZusrNmnpA7/kuDeNBo4kf7y8Hg8fsKyb3fiVckcDjD2eotpF+rRNY5pPAm0T5x/xPJgvo4EYfp2lJstrmzkwaeA5lMazCmDGGnZwEeMB/EZ41UlhdxQpAsNq0ktK04b0L7tbIsaKLe7c9M6HQBTna1sRgutLEUEiiOULdbrSlbkQ0114mK9k3spJE/FIqtiUehI+MNWeWL1TciJSCTR8Ihgg5lQ/6iEm5s6qnoXL2Q/e9RmTyiq8KOF+NCQ6H87jlnJlpeQqczV3Ytc9/hNcHEK1QxaUPUDq7rkod9lnmwsXGVC50wc1OS2vLGeZ+4B8tAP88AsFlt2NU+e4OR+rKPDVNWBhoQ5C6P9SNDQz/qukeVYAcRTH7Na4EnIl3jdkUwjACPH17DEHCuD9Vx1oVD/V587aTFbEDMPRxqC3dCwGtQlelYQY0UspwI=
branches:
  except:
  - gh-pages
notifications:
  email: false
sudo: false
cache:
  directories:
  - "$HOME/.gradle"
